[package]
name = "ctest"
version = "0.4.11"
description = "Automated tests of FFI bindings."
exclude = ["CHANGELOG.md"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/libc"
rust-version = "1.63.0"

[dependencies]
garando_syntax = "0.1"
cc = "1.0.1"
rustc_version = "0.4"
indoc = "2.0.6"

# FIXME(msrv): These should be moved to the root Cargo.toml as `[workspace.lints.*]`
#              once MSRV is above 1.64 and replaced with `[lints] workspace=true`

[lints.rust]
# FIXME(cleanup): make ident usage consistent in each file
unused_qualifications = "allow"

[lints.clippy]
# FIXME(clippy): fix these
doc_lazy_continuation = "allow"
if_same_then_else = "allow"
needless_borrow = "allow"
needless_borrowed_reference = "allow"
needless_borrows_for_generic_args = "allow"
needless_lifetimes = "allow"
only_used_in_recursion = "allow"
option_as_ref_deref = "allow"
type_complexity = "allow"
useless_format = "allow"
